### ISSUE TITLE
Could we make this repo a public repo so CodeQL can work properly?

### ISSUE THREAD

**Issue by lonegunmanb** [oribenartzyM/terraform-azurerm-mdc#9]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

@oribenartzyM I found that pr-check job in this repo's CI pipeline failed with a weird error message, after some debugging I found that our current CodeQL step could only work with a public repo, it would require extra setup to make it work with a private repo. Could you please turn this repo to public so our pipeline could work? Thanks!

**Comment by oribenartzyM** [comment]
Hey, I turned this repo to public as your request.
Thanks for your help.
